version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
    - yarn install
  build:
    commands:
      - yarn run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .next
