/* eslint-disable jsx-a11y/anchor-is-valid */
// import { ConnectButton } from '@rainbow-me/rainbowkit';
import { Box, Flex, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import { Assets, Home as HomeAssets, ProjectCards } from '@/assets';
import BottomContainer from '@/components/Home/BottomContainer';
import Carousel from '@/components/Home/Carousel';
import FloatingCard from '@/components/Home/FloatingCards';
import HeroSection from '@/components/Home/HeroSection';
import ProjectCard from '@/components/Projects/ProjectCard';
import styles from '@/styles/Home.module.scss';
import { ProjectCardData } from '@/utils/common';
import { formatNumber } from '@/utils/helpers';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Nonce Starter App</title>
				<meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
				<link href="/favicon.ico" rel="icon" />
			</Head>

			<Box
				position={'absolute'}
				top={0}
				w={'full'}
				zIndex={-1}
				sx={{
					display: { base: 'block', md: 'none' },
				}}
			>
				<Image
					src={HomeAssets.MobileGrid}
					className="h-[1000px] sm:h-[800px]  w-full "
					alt="MobileGrid"
				/>
			</Box>
			<Box position={'relative'}>
				<HeroSection />
			</Box>

			<Flex
				flexDirection={'column'}
				justifyContent={'center'}
				gap={4}
				pt={20}
				sx={{
					bg: { base: '#0c0d0d', md: 'transparent' },
				}}
				position={'relative'}
				className=" min-h-screen items-center "
			>
				<Box maxW={'769px'} placeItems={'center'}>
					<Text variant={'simple'} color={'white'} textAlign={'center'}>
						Funded Projects Already
					</Text>
					<Text
						variant={'gradient'}
						textAlign={'center'}
						sx={{
							fontSize: { base: 32, md: 48 },
						}}
					>
						Empower product devs and help them master their craft
					</Text>
				</Box>
				<Flex
					flexDirection={'row'}
					wrap={'wrap'}
					display={{ base: 'none', lg: 'flex' }}
					justifyContent={'center'}
					rowGap={5}
					py={10}
					px={8}
				>
					{ProjectCardData.map((item, index) => {
						return (
							<ProjectCard
								key={index}
								projectName={item.projectName}
								description={item.description}
								projectLogo={Assets.ProjectLogo}
								projectImage={ProjectCards.Project1}
								badgeType="soldOut" // Can be 'comingSoon', 'whitelisting', 'soldout', etc.
								badgeLabel="Sold Out"
								tokenSymbol={item.tokenSymbol}
								tokenLogo={Assets.EthLogo}
								totalRaise={formatNumber(item.totalRaise)}
								personalAllocation={item.personalAllocation}
							/>
						);
					})}
				</Flex>
				<Box
					sx={{
						w: '100%',
						display: { base: 'Box', md: 'none' },
						minH: { base: '50vh', md: '100vh' },
					}}
				>
					<Carousel />
				</Box>
				<BottomContainer />

				<FloatingCard />

				<div className="hidden xl:block absolute bottom-36  w-56 h-56 bg-purple-500 rounded-full blur-[100px] z-0 left-0  mx-auto "></div>
				<div className="hidden xl:block  absolute bottom-10  w-40 h-40 bg-purple-500 rounded-full blur-[100px] z-0 right-0  mx-auto "></div>
			</Flex>

			<footer className={styles.footer}>
				<Image src={Assets.FooterLogo} className="h-9 w-auto" alt="FooterLogo" />
				<Flex alignItems="center" justifyContent="center" gap={2} wrap="wrap">
					<Text variant="simple">© 2024 NonceStarter. All rights reserved.</Text>
					<Flex gap={2}>
						<Text as="a" href="/privacy-policy" variant="simple" cursor="pointer">
							Privacy Policy
						</Text>
						<Text as="a" href="/terms-of-service" variant="simple" cursor="pointer">
							Terms of Service
						</Text>
						<Text as="a" href="/contact-us" variant="simple" cursor="pointer">
							Contact Us
						</Text>
					</Flex>
				</Flex>
			</footer>
		</>
	);
};

export default Home;
